version: 1
disable_existing_loggers: False
formatters:
  info:
    format: "[%(asctime)s][%(levelname)-8s][%(name)s] %(message)s"
  debug:
    format: "[%(asctime)s][%(levelname)-8s][%(filename)s:%(lineno)-2d] %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: info
        stream: ext://sys.stdout

    debug_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: debug
        filename: logs/log_debug.log
        maxBytes: 10485760  # 10MB
        backupCount: 10
        encoding: utf8

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: WARNING
        formatter: debug
        filename: logs/log_errors.log
        maxBytes: 10485760  # 10MB
        backupCount: 10
        encoding: utf8

root:
    level: DEBUG
    handlers:
    - console
    - debug_file_handler
    - error_file_handler